import Header from '@/components/Header';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: `ZenTechie's Portfolio`,
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='bg-white text-black h-screen overflow-y-scroll relative'>
          <Header />
          {children}
          <div id='wrapper' className='max-h-max relative'/>
          <Footer />
        </div>
      </body>
    </html>
  );
}
